[project]
name = "nominal_iads"
version = "0.0.1"
description = "Shared scripts with stratolaunch users to process and ingest iads data into nominal"
authors = []
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "click>=8.1.7,<9",
    "conjure-python-client==2.8.0",
    "matplotlib>=3.10.3",
    "nominal-api-protos>=0.703.0",
    "nominal-dataframe-streamer==0.10.1",
    "nominal[protos]==1.75.0",
    "protobuf>=6.31.0",
    "pyarrow>=21,<22",
    "pydantic>=2.0,<3",
    "scipy>=1.15.3",
    "typing-extensions>=4,<5",
]
classifiers= [
    "Private :: Do Not Upload"
]

[tool.uv]
dev-dependencies = [
    "jupyter>=1.1.1,<2",
    "jupyterlab>=4.3.0,<5",
    "mypy>=1.13.0,<2",
    "pandas-stubs~=2.0",
    "ruff>=0.7.1,<1",
    "ipykernel>=6.29.5,<7",
    "pydantic>=2.10.5",
]

# Relies upon IADs .dlls being installed on the system, which only support 64-bit windows.
environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
]

[tool.uv.sources]
nominal-dataframe-streamer = { path = "nominal_iads/vendored/nominal_dataframe_streamer-0.10.1-cp310-abi3-win_amd64.whl" }

[project.scripts]
nominal_iads = "nominal_iads.cli.main:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
    "README.md",
    "CHANGELOG.md",
    "nominal_iads/*",
]

[tool.hatch.build.targets.wheel]
include = [
    "README.md",
    "CHANGELOG.md",
    "nominal_iads/*",
]

[tool.ruff]
line-length = 120
include = ["nominal_iads/**/*.py", "notebooks/**/*.ipynb"]

[tool.ruff.lint.pylint]
max-args = 10

[tool.ruff.lint]
# See rules and codes: https://docs.astral.sh/ruff/rules/
select = [
    "F",    # pyFlakes
    "E",    # pycodestyle (Err)
    "W",    # pycodestyle (Warn)
    "D",    # pyDocstyle
    "I001", # Isort
    "FIX",  # Flake8-FIXme
    "PL",   # PyLinT
    "NPY",  # NumPY
    "T100"  # debugger
]

extend-select = [
    "D417"  # no missing arguments
]  
ignore = [
    "FIX002",  # Ignore TODOs
    "D203",    # one-blank-line-before-class
    "D205",    # 1 blank line between summary and description
    "D213",    # multiline-summary-docs
    "D103",    # missing-class-docstring
    "D102",    # missing-public-method-docstring
    "D101",    # missing-public-class-docstring
    "D100",    # missing-module-docstring 
    "D104",    # missing-package-docstring
    "D400",    # doc line ends in period
    "D415",    # doc line ends in punctuation
    "D401",    # imperative mood
    "PLW0603", # globals
    "PLR2004",  # magic values
]

[tool.mypy]
strict = true
packages = ["nominal_iads"]
exclude = ["nominal_iads/iads_parser/lib"]

[[tool.mypy.overrides]]
module = "win32com.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pythoncom.*"
ignore_missing_imports = true
