on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  release:
    types: [published, edited]
  workflow_dispatch:
  create:

jobs:
  linux-build:
    name: Wrapper Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ["cp39-cp39", "cp310-cp310", "cp311-cp311", "cp312-cp312"] 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set script permissions
      run: chmod +x pypackage/build-wheel-linux.sh

    - name: Build the Linux wheels
      run: |
        sudo docker run --rm -e PYTHON_VERSION=${{ matrix.pyversion }} -v `pwd`:/io quay.io/pypa/manylinux_2_28_x86_64 /io/pypackage/build-wheel-linux.sh
        # cleanup for custom runner
        sudo chown -R $(whoami):$(whoami) .
    - name: Publish to PyPI
      run: |
        pip install twine==6.1.0 packaging==24.2
        twine upload wheelhouse/*manylinux*.whl
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
